// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storm/storm.proto

package storm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SummarizeRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummarizeRequest) Reset()         { *m = SummarizeRequest{} }
func (m *SummarizeRequest) String() string { return proto.CompactTextString(m) }
func (*SummarizeRequest) ProtoMessage()    {}
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dcc2fe9297aa699, []int{0}
}

func (m *SummarizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummarizeRequest.Unmarshal(m, b)
}
func (m *SummarizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummarizeRequest.Marshal(b, m, deterministic)
}
func (m *SummarizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummarizeRequest.Merge(m, src)
}
func (m *SummarizeRequest) XXX_Size() int {
	return xxx_messageInfo_SummarizeRequest.Size(m)
}
func (m *SummarizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SummarizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SummarizeRequest proto.InternalMessageInfo

func (m *SummarizeRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SummarizeResponse struct {
	Summary              string   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummarizeResponse) Reset()         { *m = SummarizeResponse{} }
func (m *SummarizeResponse) String() string { return proto.CompactTextString(m) }
func (*SummarizeResponse) ProtoMessage()    {}
func (*SummarizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dcc2fe9297aa699, []int{1}
}

func (m *SummarizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummarizeResponse.Unmarshal(m, b)
}
func (m *SummarizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummarizeResponse.Marshal(b, m, deterministic)
}
func (m *SummarizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummarizeResponse.Merge(m, src)
}
func (m *SummarizeResponse) XXX_Size() int {
	return xxx_messageInfo_SummarizeResponse.Size(m)
}
func (m *SummarizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SummarizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SummarizeResponse proto.InternalMessageInfo

func (m *SummarizeResponse) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func init() {
	proto.RegisterType((*SummarizeRequest)(nil), "SummarizeRequest")
	proto.RegisterType((*SummarizeResponse)(nil), "SummarizeResponse")
}

func init() {
	proto.RegisterFile("storm/storm.proto", fileDescriptor_4dcc2fe9297aa699)
}

var fileDescriptor_4dcc2fe9297aa699 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x2e, 0xc9, 0x2f,
	0xca, 0xd5, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x4a, 0x6a, 0x5c, 0x02, 0xc1, 0xa5,
	0xb9, 0xb9, 0x89, 0x45, 0x99, 0x55, 0xa9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42,
	0x5c, 0x2c, 0x25, 0xa9, 0x15, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92,
	0x2e, 0x97, 0x20, 0x92, 0xba, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x09, 0x2e, 0xf6, 0x62,
	0xb0, 0x60, 0x25, 0x54, 0x2d, 0x8c, 0x6b, 0xe4, 0xc4, 0xc5, 0x13, 0x0c, 0xb2, 0x25, 0x38, 0xb5,
	0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x88, 0x8b, 0x13, 0xae, 0x5d, 0x48, 0x50, 0x0f, 0xdd, 0x4a,
	0x29, 0x21, 0x3d, 0x0c, 0xd3, 0x93, 0xd8, 0xc0, 0x2e, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x10, 0xe2, 0xa0, 0xb0, 0xb6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StormServiceClient is the client API for StormService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StormServiceClient interface {
	Summarize(ctx context.Context, in *SummarizeRequest, opts ...grpc.CallOption) (*SummarizeResponse, error)
}

type stormServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStormServiceClient(cc grpc.ClientConnInterface) StormServiceClient {
	return &stormServiceClient{cc}
}

func (c *stormServiceClient) Summarize(ctx context.Context, in *SummarizeRequest, opts ...grpc.CallOption) (*SummarizeResponse, error) {
	out := new(SummarizeResponse)
	err := c.cc.Invoke(ctx, "/StormService/Summarize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StormServiceServer is the server API for StormService service.
type StormServiceServer interface {
	Summarize(context.Context, *SummarizeRequest) (*SummarizeResponse, error)
}

// UnimplementedStormServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStormServiceServer struct {
}

func (*UnimplementedStormServiceServer) Summarize(ctx context.Context, req *SummarizeRequest) (*SummarizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Summarize not implemented")
}

func RegisterStormServiceServer(s *grpc.Server, srv StormServiceServer) {
	s.RegisterService(&_StormService_serviceDesc, srv)
}

func _StormService_Summarize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StormServiceServer).Summarize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StormService/Summarize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StormServiceServer).Summarize(ctx, req.(*SummarizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StormService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StormService",
	HandlerType: (*StormServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Summarize",
			Handler:    _StormService_Summarize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storm/storm.proto",
}
