# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import morbius_pb2 as morbius__pb2


class MorbiusServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Sentiment = channel.unary_unary(
        '/MorbiusService/Sentiment',
        request_serializer=morbius__pb2.SentimentRequest.SerializeToString,
        response_deserializer=morbius__pb2.SentimentResponse.FromString,
        )


class MorbiusServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Sentiment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MorbiusServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Sentiment': grpc.unary_unary_rpc_method_handler(
          servicer.Sentiment,
          request_deserializer=morbius__pb2.SentimentRequest.FromString,
          response_serializer=morbius__pb2.SentimentResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MorbiusService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
