# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morbius.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='morbius.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rmorbius.proto\" \n\x10SentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"L\n\x11SentimentResponse\x12\x14\n\x0cmodel_result\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t2D\n\x0eMorbiusService\x12\x32\n\tSentiment\x12\x11.SentimentRequest\x1a\x12.SentimentResponseb\x06proto3'
)




_SENTIMENTREQUEST = _descriptor.Descriptor(
  name='SentimentRequest',
  full_name='SentimentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='SentimentRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=49,
)


_SENTIMENTRESPONSE = _descriptor.Descriptor(
  name='SentimentResponse',
  full_name='SentimentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_result', full_name='SentimentResponse.model_result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='SentimentResponse.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='SentimentResponse.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['SentimentRequest'] = _SENTIMENTREQUEST
DESCRIPTOR.message_types_by_name['SentimentResponse'] = _SENTIMENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SentimentRequest = _reflection.GeneratedProtocolMessageType('SentimentRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENTIMENTREQUEST,
  '__module__' : 'morbius_pb2'
  # @@protoc_insertion_point(class_scope:SentimentRequest)
  })
_sym_db.RegisterMessage(SentimentRequest)

SentimentResponse = _reflection.GeneratedProtocolMessageType('SentimentResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENTIMENTRESPONSE,
  '__module__' : 'morbius_pb2'
  # @@protoc_insertion_point(class_scope:SentimentResponse)
  })
_sym_db.RegisterMessage(SentimentResponse)



_MORBIUSSERVICE = _descriptor.ServiceDescriptor(
  name='MorbiusService',
  full_name='MorbiusService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=129,
  serialized_end=197,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sentiment',
    full_name='MorbiusService.Sentiment',
    index=0,
    containing_service=None,
    input_type=_SENTIMENTREQUEST,
    output_type=_SENTIMENTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MORBIUSSERVICE)

DESCRIPTOR.services_by_name['MorbiusService'] = _MORBIUSSERVICE

# @@protoc_insertion_point(module_scope)
